[project]
name = "nutrition-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.8.4",
    "fastapi>=0.135.1",
    "google>=3.0.0",
    "jupyter>=1.1.1",
    "pillow>=12.2.0",
    "scikit-image>=0.26.0",
    "scipy>=1.17.1",
    "tqdm>=4.67.3",
    "ultralytics>=8.4.38",
    "uvicorn>=0.42.0",
]

[tool.uv.workspace]
members = [
    "ai/sam2_annotator",
]
