### Signup

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "a@b.com",
    "password": "password123",
    "name": "John Doe"
}

### Signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "thomasrudge2@me.com",
    "password": "12345678"
}

### Delete a user OR CMD+S in the db
DELETE http://localhost:3000/users/d2dc33e3-6c7e-4bc5-9a8a-1e8a2a724fa5

