### Signup

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "a@b.com",
    "password": "password123",
    "name": "John Doe"
}

### Signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "a@b.com",
    "password": "password123"
}

### Delete a user OR CMD+S in the db
DELETE http://localhost:3000/users/1cb45710-9df6-4689-a33e-3c196b5231d0

